#theme: jekyll-theme-cayman
remote_theme: rundocs/jekyll-rtd-theme
title: Welcome to jmge's home page!

lsi: false
safe: true

incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  
