#theme: jekyll-theme-chirpy
theme: jekyll-rtd-theme
title: Welcome!

lsi: false
safe: true

incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
